# Generated by Django 3.2rc1 on 2021-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='projID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
