# Generated by Django 3.2rc1 on 2021-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('ProjectID', models.CharField(max_length=20)),
                ('Expertise', models.CharField(max_length=20)),
                ('TotalNumberProjectsDone', models.CharField(max_length=3)),
            ],
        ),
    ]
