# Generated by Django 3.2rc1 on 2021-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='EID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
