# Generated by Django 3.2rc1 on 2021-04-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_auto_20210422_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Expertise',
            field=models.CharField(max_length=30),
        ),
    ]
