# Generated by Django 3.2rc1 on 2021-05-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_alter_employee_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Image',
            field=models.CharField(default='', max_length=20),
        ),
    ]
