# Generated by Django 3.2rc1 on 2021-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0006_auto_20210504_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(default='', max_length=40),
        ),
    ]
